
-- In SESSION 1
\set AUTOCOMMIT off
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM sheet3 WHERE id = 1;

-- In SESSION 2:
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE sheet3 SET name = 'X' WHERE id = 1;
COMMIT;

-- In SESSION 2:
UPDATE sheet3 SET name = 'Y' WHERE id = 1;
COMMIT;
