
-- In SESSION 1
\set AUTOCOMMIT off
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM sheet3 WHERE id > 3;

--In SESSION 2:
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
INSERT INTO sheet3 VALUES (5, 'Test 1');
COMMIT;

-- In SESSION 3:
INSERT INTO sheet3 VALUES (6, 'Fay');
