
-- In SESSION 1
\set AUTOCOMMIT off
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM sheet3 WHERE id > 10;
-- In SESSION 2:
BEGIN;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
INSERT INTO sheet3 VALUES (11, 'NewRow');
COMMIT;

-- In SESSION 1
INSERT INTO sheet3 VALUES (12, 'New Row 2');
COMMIT;
