
-- In SESSION 1
\set AUTOCOMMIT off
BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM sheet3 WHERE id = 2;

-- In SESSION 2:
 BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
UPDATE sheet3 SET name = 'Sophie' WHERE id = 2;
COMMIT;

-- In SESSION 1
UPDATE sheet3 SET name = 'Tom' WHERE id = 2;
COMMIT;
